# reusable workflow triggered by other actions
name: CI

on:
  workflow_call:

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-20.04

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get install python3-pip
        python3 -m pip install tox

    - name: Lint code
      run: tox -e lint

  unit:
    name: Unit Test
    runs-on: ubuntu-20.04

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get install python3-pip tox

    - name: Run unit tests
      run: tox -e unit
